#!/bin/sh
#
# flower        Startup script for flower
#
# chkconfig: - 85 15
# processname: flower
# pidfile: /var/run/flower.pid
# description: celery flower
#
### BEGIN INIT INFO
# Provides: flower
# Required-Start: $local_fs $remote_fs $network
# Required-Stop: $local_fs $remote_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop flower
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

flower="/usr/local/bin/flower"
prog=`/bin/basename $flower`
logdir="/var/log/$prog"
logfile="/var/log/$prog/$prog.pid"
pidfile="/var/run/$prog.pid"
lockfile="/var/lock/subsys/$prog"
loglevel="warning"
port="5555"
broker="shared-redis-001.p.use1.risingtidegames.com"
python_bin="/usr/bin/python27"
flower_bin=$flower

start() {
    echo -n $"Starting $prog: "
    $python_bin $flower_bin --port=$port --broker=redis://$broker --auto_refresh=True --log_file_prefix=$logfile --logging=$loglevel
    RETVAL=$?
    sleep 1
    echo
    [ $RETVAL = 0 ] && touch ${lockfile}
    PID=`netstat -anlp | grep 0.0.0.0:5555 | awk '{print $7}' | cut -f1 -d"/"` 
    echo $PID > $pidfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p ${pidfile} ${prog}
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
}

reload() {
    echo -n $"Reloading $prog: "
    killproc -p ${pidfile} ${prog} -HUP
    RETVAL=$?
    echo
}

rh_status() {
    status -p ${pidfile} ${flower}
}


if [ ! -d $logdir ]
then
    mkdir -p $logdir
fi

case "$1" in
    start)
        rh_status >/dev/null 2>&1 && exit 0
        start
        ;;
    stop)
        stop
        ;;
    status)
        rh_status
        RETVAL=$?
        ;;
    restart)
        stop
        start
        ;;
    upgrade)
        rh_status >/dev/null 2>&1 || exit 0
        upgrade
        ;;
    reload)
        reload
        ;;
    *)
        echo $"Usage: $prog {start|stop|restart|reload|status|help}"
        RETVAL=2
esac
exit $RETVAL
