#! /bin/sh
# chkconfig:   - 20 80

### BEGIN INIT INFO
# Provides:       graphite
# Required-Start: $remote_fs $network
# Required-Stop:  $remote_fs $network
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:       An init script for Graphite's carbon-cache daemon.
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions
RETVAL=0
/etc/init.d/carbon-cache $1
VAL1=$(expr $RETVAL + $?)
/etc/init.d/carbon-aggregator $1
VAL2=$(expr $VAL1 + $?)
/etc/init.d/carbon-relay $1
VAL3=$(expr $VAL2 + $?)
/etc/init.d/uwsgi $1
VAL4=$(expr $VAL3 + $?)
exit $VAL4
