#! /bin/sh
# chkconfig:   - 20 80

### BEGIN INIT INFO
# Provides:       graphite-web
# Required-Start: $remote_fs $network
# Required-Stop:  $remote_fs $network
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    An init script for uwsgi daemon
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

set -e

export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME="uwsgi"
DAEMON="/usr/local/bin/$NAME"
CONFIGFILE="/opt/graphite/conf/$NAME.ini"
PIDFILE="/var/run/$NAME.pid"
LOGFILE="/var/log/uwsgi/${NAME}.log"
ERRORLOG="/var/log/uwsgi/${NAME}_error.log"
OP=$1

if [ ! -d "/var/log/uwsgi" ]
then
    mkdir -p /var/log/uwsgi
fi
chown -R nginx:nginx /var/log/uwsgi

set -e
[ -x "$DAEMON" ] || exit 0

start() {
    if [ -f "$PIDFILE" ];then
        echo "${NAME} Service already running"
    exit 1
    else
        echo "Starting $NAME"
        $DAEMON --ini  $CONFIGFILE \
            --logto2 $LOGFILE \
            --log-ioerror $ERRORLOG \
            --pidfile $PIDFILE > /dev/null 2>&1
        RETVAL="$?"
    fi
}

stop() {
    if [ ! -f "$PIDFILE" ]; then
    if [ "$OP" != "restart" ]
    then
            echo "${NAME} Service not running"
        exit 2
    fi
    else
    echo "Stopping $NAME"
        rm -f $PIDFILE
        for i in `ps -ef | grep $DAEMON | grep -v grep | awk '{print $2}'`
        do 
            kill -9 $i > /dev/null 2>&1
        done
        RETVAL="$?"
    fi
}

status() {
    if [ -f "$PIDFILE" ];then
        echo "${NAME} Service is running"
    exit 0
    else
        echo "${NAME} Service is not running"
    exit 3
    fi
}

case "$OP" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    status)
        status
    ;;
    restart)
        stop
        sleep 1 
        start
    ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 3
esac
exit $RETVAL
