#!/bin/bash

SVN_URL="svn+ssh://jenkins@svn.risingtidegames.com/repos/ops/RPMS"
#Src rpm name and path#
SRC=$1
#destination dir (preferrably the trunk of subversion.) no trailing '/' needed.
DST=/tmp
#short name for hudson job.
SHORT=`basename $1|perl -p -i -e 's/-\d+.*//g'`
#make the dir
echo "Making: $DST/$SHORT/{SRPMS,SPECS,BUILD,SOURCES}................"
mkdir -p $DST/$SHORT/{SPECS,BUILD,SOURCES}
CUR=`pwd`
#go to the dest.
cd $DST/$SHORT
/usr/bin/svn --no-auth-cache co $SVN_URL/$SHORT/SRPMS
#extract the goodies
echo "Extracting src.rpm contents......."
rpm2cpio $SRC | cpio -i -d -m -v 
#find the spec file (should ONLY be 1 per rpm)
find . -maxdepth 1 -type f -name *.spec -exec mv {} SPECS/$SHORT.spec \;
#move the rest into the sources dir.
find . -maxdepth 1 -type f -exec mv {} SOURCES/ \;
#add it to subverison....
/usr/bin/svn --no-auth-cache import $SVN_URL/$SHORT -m "adding ${SHORT}"
#go back
cd $CUR
